# @generated: Generated with gen_build_npm.py

package(default_visibility = ['//visibility:public'])

load('@org_dropbox_rules_node//node:defs.bzl', 'npm_library')

npm_library(
    name = 'is-number',
    npm_req = 'is-number@5.0.0',
    shrinkwrap = 'npm-shrinkwrap.json',
    contents = [
        'is-number/LICENSE',
        'is-number/README.md',
        'is-number/index.js',
        'is-number/package.json',
    ],
)