# @generated: Generated with gen_build_npm.py

package(default_visibility = ['//visibility:public'])

load('@org_dropbox_rules_node//node:defs.bzl', 'npm_library')

npm_library(
    name = 'object-assign',
    npm_req = 'object-assign@4.1.1',
    shrinkwrap = 'npm-shrinkwrap.json',
    contents = [
        'object-assign/index.js',
        'object-assign/license',
        'object-assign/package.json',
        'object-assign/readme.md',
    ],
)